name: servarr
services:
  seerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: seer
    restart: unless-stopped
    network_mode: service:gluetun

    # ports:
    #   - 5055:5055 # Seer

    environment:
      - LOG_LEVEL=debug
      - TZ=$TZ

    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config/seerr
        target: /config

    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run as specified uid.
        - container: PGID
          description:
            en_us: Run as specified gid.

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: seerr
  category: MTI
  developer: Seer Developers
  author: MTI
  tagline:
    en_US: Request Your Media Library.
  description:
    en_US: Requesting the expansion of your media library.
  tips:
    before_install:
      en_US: Requires Gluetun already be installed.
  icon: https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Seerr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Seerr/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Seerr/thumbnail.png
  scheme: http
  index: /
  title:
    en_US: Seerr (VPN)
  port_map: "5055"
