name: unmanic
services:
  unmanic:
    container_name: unmanic
    image: josh5/unmanic:latest
    restart: unless-stopped
    network_mode: bridge

    devices:
      - /dev/dri:/dev/dri # For H/W transcoding using the VAAPI encoder

    ports:
      - 8888:8888

    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ

    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/cache
        target: /tmp/unmanic
      - type: bind
        source: /DATA/Media
        target: /library

    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run as specified uid.
        - container: PGID
          description:
            en_us: Run as specified gid.

      volumes:
        - container: /config
          description:
            en_us: Config directory.
        - container: /tmp/unmanic
          description:
            en_us: Cache directory.
        - container: /library
          description:
            en_us: Media directory.

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: unmanic
  category: MTI
  developer: Unmanic Developers
  author: MTI
  tagline:
    en_US: Optimize Your Media Library.
  description:
    en_US: Convert and optimize your media library.
  icon: https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Unmanic/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Unmanic/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Unmanic/thumbnail.png
  scheme: http
  index: /
  title:
    en_US: Unmanic
  port_map: "8888"
