name: caddy
services:
  app:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    volumes:
      - /DATA/AppData/$AppID/data:/data
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/Caddyfile:/etc/caddy/Caddyfile

x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Caddy - The Ultimate Server with Automatic HTTPS.
  tagline:
    en_us: Caddy - The Ultimate Server With Automatic HTTPS.
  developer: ''
  author: mti
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/webp/caddy.webp
  title:
    en_us: Caddy
  category: Network
  port_map: '80'
