name: bazzarr
services:
  cleanuparr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazzarr
    restart: unless-stopped
    network_mode: service:gluetun

    # ports:
    #   - 6767:6767

    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Media/Movies
        target: /data/movies
      - type: bind
        source: /DATA/Media/TV\ Shows
        target: /data/tv

    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ

    x-casaos:
      envs:
        - container: TZ
          description:
            en_us: TimeZone
        - container: PUID
          description:
            en_us: Run as specified uid.
        - container: PGID
          description:
            en_us: Run as specified gid.

      volumes:
        - container: /config
          description:
            en_us: Config directory.
        - container: /movies
          description:
            en_us: Movies directory.
        - container: /tv
          description:
            en_us: Shows directory.

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: bazzarr
  category: MTI
  developer: Bazzarr Developers
  author: MTI
  tagline:
    en_US: Subtitles always.
  description:
    en_US: Getting subtitles for your media library.
  tips:
    before_install:
      en_US: Requires Gluetun already be installed.
  icon: https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Bazzarr/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Bazzarr/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/micahilbery/mti-zima-appstore@main/Apps/Bazzarr/thumbnail.png
  scheme: http
  index: /
  title:
    en_US: Bazzarr (VPN)
  port_map: "6767"
